# Generated by Django 2.2.16 on 2022-06-14 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-pub_date'], 'verbose_name': 'comment', 'verbose_name_plural': 'comments'},
        ),
    ]
